#配置端口号
server:
  port: 8081
  #根路径设置
  #servlet:
    #context-path: /kuang
spring:
  web:
    resources:
      static-locations: /static

  #关闭缓存
  thymeleaf:
    cache: false

  #配置i18n文件
  messages:
    basename: i18n.login
